### ISSUE TITLE
Provide a way to clear out the challenge for a ticket

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#127]
As a last resort, if the backing challenge gets out of whack, we want to remove the Topcoder challenge for a ticket and start over.  This should be a new page in the app somewhere - maybe under a given project?

The user should be able to copy in the URL to the ticket and then we will:

* Remove the MongoDB entry for the Git issue
* ~~Move the current challenge to "cancelled"~~. This is not feasible and isn't currently required
* Add a checkbox to re-create the challenge for the Git issue
  * If checked: go through the flow to create a *new* challenge for the Git issue.
  * If unchecked: Just remove the MongoDB entry

**Comment by jmgasper** [comment]
@rootelement - This one turned into a service related nightmare.  The problem in the challenge service is that you can't mark a challenge as "cancelled" without *activating* it, but we don't actually activate anything until we go to actually pay a ticket.  I asked if we could just mark a challenge as "deleted" through the API, which would align with what we do in OR for gameplanning, but I was told that the current V3/V4 challenge API does *not* support marking a draft challenge as deleted.

I think the best approach, due to those limitations, is just to delete the current Mongo / DynamoDB entry for the ticket and have the system create a new one, leaving an "orphaned" challenge in the system.

**Comment by jmgasper** [comment]
Confirmed that we can just delete the current DynamoDB entry for the ticket and allow the processor to create a new one.

**Comment by rootelement** [comment]
Yes, update this issue to do just this.

From the Manage page mentioned in this issue (https://github.com/topcoder-platform/topcoder-x-ui/issues/191), show a list of the challenges associated to the project with their current status/label, and if the user is an admin*, show a "recreate challenge" button that:
 - UI Alerts the user that it will orphan the challenge in direct
 - Reopens the issue if necessary?
 - Removes the git tcx labels
 - Removes the assigned user
 - Deletes the association in the issues table
 - Sets the Open for Pickup label in git
 - Assigns the User

*If we don't have user roles in the UI right now, this can be visible for everyone

**Comment by jmgasper** [comment]
Opened a new ticket for the flow above.
