### ISSUE TITLE
Failure when creating challenge

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#13]
This was what I saw in testing:

1. Create a ticket in Gitlab
2. Processor attempts to create the challenge, but failed due to an issue in the TC API
3. Any further update failed to the ticket - assignee, prize, etc... because there was no backing challenge

We need to do the following:

1.  On an error in creating or updating a challenge (basically any TC API error) - write a message back as a comment to the Gitlab or Github ticket indicating the details of the failure (error message and HTTP code)

2.  We'll update the JSON that we send to Kafka to include a new "processedSuccessfully" flag.  Once we know that a message has been processed successfully, we will set this flag to "true".  If it's set to false, we can retry the operation at a configurable interval until it completes successfully.  

3.  We will also update the JSON for kafka messages to include a "retryCount" field.  This will be an integer value that indicates how many times an action has been retried.  To avoid DDOS where things are just retried over and over again, we will cut off the retries at a configurable value, like 3 or 5, at which point no more retries will be done.

**Comment by veshu** [comment]
@jmgasper how exactly the processedSuccessfully flag should work. I see no use of this unless we are again sending the message back to kafka when successfull operation.

Do we need to send the event detail to kafka even after processed succesffully? if not we can simply increase the retryCount and sent to kafka, which will be tried again.

**Comment by jmgasper** [comment]
Ok - setting the retryCount and posting back to Kafka makes sense - let's do that.
