### ISSUE TITLE
Add page to allow for adding tickets to Gitlab / Github

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#147]
Topcoder has requested a new page in Topcoder-X that allows a user to add a ticket to Gitlab or Github.

The user should be able to:

1.  Open up the `Add Issue` form
2.  Select the project that the issue will be added to
3.  Enter a dollar amount
4.  Enter a title (minus the dollar amount)
5.  Enter the issue text

On clicking `Submit`, the UI will:

1.  Create a ticket in either Gitlab or Github (depending on the selected project) with the title formatted correctly for TC-X `[$<amount>] <Title>`, and the description.  
2.  Add label `tcx_OpenForPickup` to the new ticket
3.  Display a success message to the user like `Issue #199 has been created`, where text `Issue #199` is a link to the Gitlab / Github ticket they can click on.

Further edits and adding attachments will be done via Gitlab / Github.

**Comment by alamora** [comment]
Perfect
