### ISSUE TITLE
Allow revoking / reloading github / gitlab tokens

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/topcoder-x-ui#150]
I find that I am unable to use any of the self sign up links for gitlab (and I think even github) because the token might be no longer applicable and needs a refresh or re-generated...

For example, accessing a self sign up link (that I created or from some other project) gives me this error:

![image](https://user-images.githubusercontent.com/2317133/62103173-418d8b80-b2b9-11e9-968c-ce412a8033b6.png)

It would be nice if the UI provides an option to delete the existing link between our github / gitlab accounts and Topcoder X to regenerate it. I think that will resolve my above issue

### Implementation

On the settings tab, we'll add a red "X" button next to each item, *if* it's already set up.  For instance, if there's a checkmark indicating that Github is set up, we'll also show a red "X" button to revoke that token.

On clicking the red "X", there should be a prompt for the user to confirm, like `Are you sure you want to revoke the authorization token for Github?`, `Yes`, `No`.

<img width="521" alt="Screen Shot 2019-07-30 at 3 37 23 pm" src="https://user-images.githubusercontent.com/21790/62103565-26824200-b2e0-11e9-9c77-405f866dc1ca.png">

**Comment by jmgasper** [comment]
@callmekatootie - Thanks.  I'll add this to the next challenge.
