### ISSUE TITLE
Update the owner of Topcoder X to be Topcoder

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/topcoder-x-ui#151]
At the moment, when we give Topcoder X permission to our github account, it shows Topcoder X by JMGasper as the app requesting permission.

I would expect it to say Topcoder X by Topcoder instead of a user.

**Comment by jmgasper** [comment]
@cwdcwd - Will probably need some help here with the app registration.

**Comment by jmgasper** [comment]
@rootelement - Do we have the prod OAuth apps created, in preparation for the prod migration?
