### ISSUE TITLE
"Invalid request parameters" when adding copilot payment

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#152]
This is seen in prod.  Something doesn't work right when adding the copilot payments.  It works fine when calling the API directly through Postman though.

<img width="2032" alt="Screen Shot 2019-07-31 at 7 30 58 am" src="https://user-images.githubusercontent.com/21790/62166932-57f12100-b365-11e9-843f-6f776c6bfd12.png">

**Comment by afrisalyp** [comment]
@jmgasper 
Can you please provide more detail about how to reproduce the error?
Did it happen on a specific project?

**Comment by afrisalyp** [comment]
@jmgasper 

It seems the project id that is seen on the screenshot looks like `mongodb object id`.

But I successfully tested on my local deployment and I found that the project id is `UUID` looks like 
`32f3f46d-d1aa-4bf4-898a-438853180e91-1564885944672`

Do you think the problem is related to it?

**Comment by jmgasper** [comment]
@afrisalyp - The code deployed on prod is the 'master' branch, which is quite a bit older.  I just want to make sure we test this with the newest code - if it can't be reproduced, that's fine.  Just make sure to document that in your README, thanks.

**Comment by afrisalyp** [comment]
@jmgasper 

I found an old issue similar to this problem.
https://github.com/topcoder-platform/topcoder-x-ui/issues/125

It has been fixed by the commit but it hasn't merged to the master branch.
So I believe this issue is already fixed.

Sure, I'll document on my README.
Thanks.
