### ISSUE TITLE
Update deployment and configuration docs with M2M token / Auth0 details

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#154]
The documentation for deployment (https://github.com/topcoder-platform/topcoder-x-ui/blob/develop/TopcoderXDeploy.md) and general configuration needs to be updated with the new values for Auth0 values used with the M2M token generation.

**Comment by afrisalyp** [comment]
@jmgasper 
Do we need to put the client id and client secret in the document?

**Comment by jmgasper** [comment]
@afrisalyp - Yes, please do.
