### ISSUE TITLE
Create labels automatically

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/topcoder-x-ui#155]
It appears that this tool requires the copilot to set some labels in the repository which is then used by this tool.

A request: Could this tool create the labels needed in the repository automatically, if they don't exist already...

**Comment by jmgasper** [comment]
@callmekatootie - This is already part of Topcoder-X.

See the `Setup of labels, webhooks, and wiki` section of the documentation:

https://github.com/topcoder-platform/topcoder-x-ui/wiki

<img width="1423" alt="Screen_Shot_2019-08-13_at_7_36_22_am" src="https://user-images.githubusercontent.com/21790/62900270-19178e00-bd9d-11e9-8f04-50f196818fd6.png">
