### ISSUE TITLE
Close challenge failure

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#18]
When we close a ticket in Gitlab or Github, the flow should be:

* When closed, the ticket is paid on the Topcoder site to the current assignee
* If there's no assignee, it will just be closed on the Topcoder site
* After the ticket is processed successfully and paid, the labels of the ticket should be changed to "Paid" and "Fix Accepted"
* A comment should be added that says "Payment task has been updated : "

We now need to think about what happens if one of these steps fails.

The main goal is to avoid a *double* payment to a member.  

#### If the payment fails on the site and the challenge is still open:

* Reopen the Gitlab / Github ticket
* Ensure the label is "Ready for review"
* Add a comment message saying "Payment failed: " + the error message from the API + the HTTP response code
* Change the JSON for the close message to add a flag: "paymentSuccessful"=false

#### If the challenge was closed successfully, but there were errors adding the comment to the Gitlab / Github ticket

* Change the JSON for the close message to add a flag saying "paymentSuccessful"=true
* Leave the kafka message in the queue and it will be retried

#### Retry limit

As with the other errors outlined here:  https://github.com/topcoder-platform/topcoder-x-ui/issues/13

We will have the same retry mechanism for these messages as well, including the limited number of retries.

**Comment by veshu** [comment]
@jmgasper For reshceduling the event for certain interval, I see following ways:
1. we use some background jobs to reschedule the event
2. save in our db and reschedule at certain interval from db

As there is no option to schedule in kafka. And relying on timeOut looks problematic as it will break if service is restarted.

**Comment by jmgasper** [comment]
@cwdcwd - Any thoughts on this?

**Comment by jmgasper** [comment]
@veshu - This is looking pretty good.

A couple things:

1.  On a second failure, let's ignore sending the comment to the Github / Gitlab issue that the payment failed.  I don't want to spam tickets with a bunch of messages.

2.  I'm seeing the ticket be re-assigned, which is redundant - see attached:

<img width="820" alt="screen shot 2018-06-22 at 11 37 20 am" src="https://user-images.githubusercontent.com/21790/41788594-b38b07f2-7611-11e8-9cd9-1bdae1ce0b8b.png">
