### ISSUE TITLE
Add Create Challenge Button from TCX-UI

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/topcoder-x-ui#191]
Change this button from Edit to Manage because there are repo setup buttons on this page.  
<img width="937" alt="Screen Shot 2019-09-24 at 1 25 10 PM" src="https://user-images.githubusercontent.com/5400156/65535130-d3d39980-dece-11e9-975a-175c75df8ff2.png">

Add a button to the Manage page that says "Create Advertisement Challenge"

Clicking that button should create a draft F2F on the project with this boilerplate text:  
https://docs.google.com/document/d/1FNteySIO8YLcgZhNoOsciMJlwSJn334F78rn1Dcz8Dg/edit 
And opens that challenge in a new tab, or provides a link to open it.

**Comment by jmgasper** [comment]
@rootelement - Any more details on this one?  Or can I start work on it?
