### ISSUE TITLE
[$80] Processing order

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#24]
If a user creates a ticket with an assignee, it seems like now we handle two separate events - one for the created event and one for assigning the user.

This caused a problem in my testing because the assignee event was processed first, before there was a challenge to assign to, and then the assignee was processed twice.

If we can handle this case and do the creation with the assignee as part of the challenge creation request, that would be preferable.

![screen shot 2018-06-30 at 1 46 18 pm](https://user-images.githubusercontent.com/21790/42128225-062ca7f8-7c6c-11e8-9eec-1a9839527052.png)

**Comment by veshu** [comment]
@jmgasper I think its not possible. as github send separate webhook for assignement.
Now we have handling assignment during create as well. but I don't see a way to find if current issue is being creating challenge or not before trying to assingn. 

One thing we can do is remove the challenge assignment during issue create and only handle during assignement event, and we could push assignement event on retry event for this case(challenge not found without showing error here and showing comment only after retry count has exceded).

Can you please bring some suggestion here how it can be implemented?

**Comment by jmgasper** [comment]
Ok - let's remove the challenge assignment during issue create.  That will better match the Github flow - we just have to make sure it also works for Gitlab.

**Comment by jmgasper** [comment]
Bumped the payment for the extra work.

**Comment by veshu** [comment]
@jmgasper fixed
