### ISSUE TITLE
Handling issues where challenge creation fails

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#28]
We have a problem when challenge creation fails, which can happen for various reasons.

If challenge creation fails for a git ticket, then future updates to that ticket also fail because there is no Topcoder challenge associated with the ticket.

### Expected functionality 

To get around this, we should do the following:

1.  On future updates to the ticket (assignee changed, ticket updated, etc...), we need to check if there is an associated challenge.  If there is no associated challenge, we should attempt to create one.  If that fails, we will log a new message as a comment on the ticket indicating that challenge creation failed.

2. We need to ensure that if an OAuth token for a user has expired that we properly refresh it.

### Current functionality

Currently, if the challenge creation fails when the ticket is created, all future updates fail when assignees are added or when the ticket is updated or closed.

### Validation

For this challenge, you *MUST* provide clear validation details for both of the items mentioned above.

**Comment by jmgasper** [comment]
@veshu  - In testing this, I see it handled for label editing and unassignment, but I don't see it working for a case where I edit the payment.

For instance, I had an existing ticket and I moved the payment from $75 to $80 and the backing challenge wasn't created.

**Comment by veshu** [comment]
@jmgasper I couldn't replicate this issue

![image](https://user-images.githubusercontent.com/2202045/43017905-8df375a2-8c77-11e8-9c3e-01838160c9c7.png)

The challenge is created only after 4 minutes for current default configurations.
