### ISSUE TITLE
Add support for multiple repo URL per project

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/topcoder-x-ui#316]
currently, if I have backend and frontend repo, I need to create two separate projects on topcoder-x making worse when there are more repositories for the same project.

Expected Result
Update the REPO URL field to support comma-separated repositories so we can handle multiple repositories with a single project.  Please ensure the prompt below the field is updated to:

`The URL to the repository on Github or Gitlab. For example: "https://github.com/topcoder-platform/topcoder-x-receiver".  Note that you can comma-separate multiple repositories in this text field`

**Comment by jmgasper** [comment]
@rootelement - What do you think about this one?
