### ISSUE TITLE
Budget Reporting

### ISSUE THREAD

**Issue by veshu** [topcoder-platform/topcoder-x-ui#324]
It would really good to have total issue prize that has been spent on current bug bash.

Can we have a simple report with following filter:
1. project
2. start period
3. end period
4. issue label(tcx label)

Result as below
Show the list of issue link with in one column and prize in another column.

Also show total prize for current filter criteria.

**Comment by jmgasper** [comment]
I think this needs to be higher up than TCX.  In TC Direct somewhere

**Comment by jmgasper** [comment]
@rootelement - Let me know your thoughts on this when you have time.  The dashboard in Topcoder-X just doesn't make a lot of sense right now, but I'm not sure what would be fully helpful there.  This could potentially be an enhancement there.

**Comment by veshu** [comment]
> I think this needs to be higher up than TCX. In TC Direct somewhere

This is really useful for budget planning on bug bashes. TCX might include TC fee and other costs and other challenges also.

For the challenges which are run from X can be best computed here. Right now there is no way to actual count of bug bash budget on anywhere except manual.

**Comment by jmgasper** [comment]
@rootelement - Should I archive this one?  Seems like this should be in connect / direct and not tcx directly.
