### ISSUE TITLE
Assigned ticket check

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#33]
The "Assigned" label isn't getting updated or handled properly when a ticket is closed:

### Expected

When a ticket is closed, we add "Fix Accepted" and "Paid" labels to the ticket after the payment has been processed.

The ticket should be moved from the "Assigned" tab in the dashboard to "Paid"

### Currently

The ticket isn't moving.  I have a ticket I used for testing, and it is closed with labels "Fix Accepted" and "Paid", but on the Dashboard it still shows as open under the "Assigned" tab.

![screen_shot_2018-07-20_at_9_26_32_am](https://user-images.githubusercontent.com/21790/42975403-51f97330-8bff-11e8-8f8b-133713dc532f.jpg)

#### Ticket

<img width="1613" alt="screen shot 2018-07-20 at 9 26 37 am" src="https://user-images.githubusercontent.com/21790/42975414-59d40cbe-8bff-11e8-9c99-c8e5d7b2b98c.png">

**Comment by veshu** [comment]
couldnt replicate. is this producable on dev as well?

**Comment by jmgasper** [comment]
@veshu - I'm testing in dev but am running into API issues.  I'll let you know. I've seen this multiple times in prod.
