### ISSUE TITLE
Does the tcx_cancelled label do anything

### ISSUE THREAD

**Issue by callmekatootie** [topcoder-platform/topcoder-x-ui#343]
Expected: When setting the `tcx_cancelled` label, the contest generated for the ticket is cancelled. Any new labels set will need to be treated as a new ticket with a new contest being created.

Current: Setting the label does nothing.

The latter bit `Any new labels set will need to be treated as a new ticket with a new contest being created.` is just an expectation for the future but the former is what I am mainly looking for.

Context: Launched a tcx based ticket - member was not able to complete it. Changed mind and will run a contest instead... Need to cancel the generated contest for the ticket through tcx - set the label but nothing happened

### For the challenge

Please ensure that this is tested and debugged so that it works properly.  

We need to ensure:

* That the `tcx_Cancelled` label is added by the UI when a new project is created, for both Gitlab and Github
* Setting label `tcx_Cancelled` and closing a ticket should cancel the backing Topcoder challenge and post a comment back to the ticket like `Challenge <id> has been cancelled`.  
* If a user reopens the ticket and assigns `tcx_OpenForPickup`, then a new backing Topcoder challenge should be created.

**Comment by jmgasper** [comment]
@callmekatootie - It will do something when we deploy the v5 API updates.  The problem with this feature in v3 was that the API to actually cancel / delete a challenge didn't work properly, so as of right now the label doesn't do anything.

**Comment by jmgasper** [comment]
Covering in #361
