### ISSUE TITLE
Unassignment not working

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#35]
Unassigning a user from a ticket isn't reflected in the Topcoder challenge that backs the Gitlab or Github ticket.

### Expected

If a ticket is currently assigned to a member and the assignee is removed / cleared, the assignee should also be *removed* from the challenge in the Topcoder API.

### Current

Right now, the assignee is added properly, but when it's removed in Gitlab / Github the backing Topcoder challenge doesn't show the change - it still shows the original assignee.

### Testing

Please ensure to test:

* Gitlab and Github
* Unassigning a user
* Changing the assignee from one member to another to ensure the assignee is updated properly

**Comment by narekcat** [comment]
@jmgasper Is this issue still actual ? I set up all three projects in my local machine, follow all instructions on REAMDME.md files and test this issue for gitlab and github. In both cases it works correctly.

**Comment by jmgasper** [comment]
Ok - please make a clear note of how you tested in your README and the reviewers will validate.

**Comment by narekcat** [comment]
Ok, thank you.

**Comment by jmgasper** [comment]
Note - I tested this again and it's still a valid issue.  Not sure how others are testing, but I've seen this in dev as well (x.topcoder-dev.com).

You can validate by:

1.  Create a ticket in a linked Github project
2.  Assign the ticket to yourself
3.  Validate that the project is shown with `Assign Member(s):` value in www.topcoder-dev.com/direct
4.  Remove the assignee in Github
5.  Observe that the project still shows an `Assign Member(s):` value in www.topcoder-dev.com


![screen_shot_2018-08-30_at_3_26_09_pm](https://user-images.githubusercontent.com/21790/44831263-18a7e500-ac69-11e8-9b71-3a05ced1730c.jpg)
