### ISSUE TITLE
'Hours assigned' value is incorrect in the dashboard

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/topcoder-x-ui#367]
**Steps**
Go to https://x.topcoder-dev.com/
Go to Dashboard
Check the Hours assigned value on the issues

The value is incorrect

![image](https://user-images.githubusercontent.com/4592712/102981470-fff52480-452e-11eb-8d4c-4214cea39af5.png)

**Comment by jmgasper** [comment]
We're going to ignore the dashboard for now - likely going to be removed altogether when we move to MFE
