### ISSUE TITLE
When sign up a user and try to log in from that user, the sign in screen is shown again. Same issue with google sign in 

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/topcoder-x-ui#369]
**Steps**
Go to https://x.topcoder-dev.com/
Click Sign up and sign up for a new account
After sign up, click the activation email
Log in from the newly created user

the sign in screen is shown again

[Screencast 2020-12-23.zip](https://github.com/topcoder-platform/topcoder-x-ui/files/5735509/Screencast.2020-12-23.zip)

When trying to sign in from a google account after a successful google account sign up also this same error occurs
[Screencast 2020-12-23.zip](https://github.com/topcoder-platform/topcoder-x-ui/files/5735552/Screencast.2020-12-23.zip)

**Comment by sdgun** [comment]
Please ignore, my mistake

**Comment by jmgasper** [comment]
@sdgun - I think this is because the new user isn't a copilot.  The Topcoder-X tool is only accessible to copilot users.

**Comment by sdgun** [comment]
@jmgasper I think testing on sign up is totally irrelevant here then.
