### ISSUE TITLE
Add column showing if copilot payment is enabled

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/topcoder-x-ui#378]
The new feature indicating if copilot payment is enabled or no is great!

![image](https://user-images.githubusercontent.com/146016/105574365-bfc2d500-5d6c-11eb-9753-b42beb2ce03e.png)

Previously to indicate for myself if copilot payment is enabled or no I had to rename to project to something like `Work Manager (no copilot)`. As now we have explicit indicator, it would be great to show in the list so we can know from the first glance where copilot payment is enabled, and where no, without opening particular project:

![image](https://user-images.githubusercontent.com/146016/105574342-999d3500-5d6c-11eb-8c19-1817ed5e9db0.png)

**Comment by jmgasper** [comment]
I like this - we'll implement it, thanks!

**Comment by sdgun** [comment]
Verified in Dev, the indicator is displayed correct when Create Copilot Payments? is selected and not selected.
