### ISSUE TITLE
Topcoder X Git repo URL Collisions

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#384]
https://github.com/topcoder-platform/topcoder-x-processor/blob/develop/services/IssueService.js#L111

That function gets the project based on the url. It gets the first one…. There’s no filter on the archived flag and if there are two active, it’ll be even worse.

- [x] The processor needs to be updated to filter on `archived: false` flag when it gets the project from Dynamo
- [x] The API needs to be updated so you can’t create a x.topcoder.com project for a repo that exists and is not archived
- [x] Show an error on project creation in the UI when attempting to create a project for a repo that exists and is not archived.  The error should include the copilot and owner name of the existing project, like `This repo already has a Topcoder-X project associated with it.  Copilot: <copilot>, Owner:<owner>`
- [x] We'll need a script that goes through the existing DB and just writes out which repos have duplicate active projects so we can get in touch with copilots and admins to fix the issues.

**Comment by sdgun** [comment]
Verified creating projects for a repo which is used in not archived project, the error message is shown as expected.

![image](https://user-images.githubusercontent.com/4592712/107626555-fdd45a00-6c83-11eb-848b-30dc83141ca1.png)
