### ISSUE TITLE
Don't update challenge after it's marked completed

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#385]
We've had a couple cases recently where challenges are being mishandled after they've been completed.  This is likely due to something failing earlier in the process and then a retry is spawned that comes in after another process has completed the challenge, causing things to become confused in the system.

Here's an example, where an assignee was removed *after* the payment was complete. 

![image](https://user-images.githubusercontent.com/21790/106817585-2af49b80-66cb-11eb-9a81-d95bb3ab35be.png)

### Fix

The fix should be that all updates to a challenge pull the challenge status *first*.  If the challenge is marked as `completed`, then any updates should be ignored.  No updates should be done to a completed challenge.

**Comment by afrisalyp** [comment]
@jmgasper 

Any available Topcoder Connect ID that we can use?
It seems 7377 and 16665 is not valid anymore.

**Comment by jmgasper** [comment]
@afrisalyp - Sorry for the trouble.  Try 17249

**Comment by afrisalyp** [comment]
@jmgasper 

When payment processing is completed, we mark the DB record status to `challenge_payment_successful`.

Can we use that flag instead of fetching the challenge status from Topcoder API for every issue event processing?

**Comment by jmgasper** [comment]
@afrisalyp - Yes, that should be fine.
