### ISSUE TITLE
Lable tcx_Paid is added but no payment was made

### ISSUE THREAD

**Issue by kylewu** [topcoder-platform/topcoder-x-ui#388]
![-3-Removal-form-Member-Date-of-birth-Two-validations-shown-only-one-is-required-·-Issue-243-·-tc-wellmark-personal-rep-ui](https://user-images.githubusercontent.com/180198/108194714-3c03ca80-7117-11eb-92be-05b1bdcf8777.png)

I have checked in OR, the challenge has no submitter.
```
Payment task has been updated: https://www.topcoder.com/challenges/f94d0c8a-612a-46e4-80d1-9b2c607b779b
Payments Complete
Winner: sontieu
Challenge f94d0c8a-612a-46e4-80d1-9b2c607b779b has been paid and closed.
```

**Comment by jmgasper** [comment]
@kylewu - When was this challenge created?

@rootelement - Seems like there's still trouble syncing the assignee?

**Comment by kylewu** [comment]
@jmgasper "started 02.12.2021 17:30 EST"

Submission phase is still open now.

https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30167699

**Comment by jmgasper** [comment]
@kylewu - I can't access that challenge, but I'm guessing that submission phase is still open because there's no submitter.  If you add a submitter manually in OR, and then close it in Direct, it'll probably fix the issue.

**Comment by kylewu** [comment]
@jmgasper right. it's fixed. thank you
