### ISSUE TITLE
Pure V5 Task - Copilot Payment with No Copilot Assigned

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/topcoder-x-ui#389]
Found this on your test repo, but it's a real case. I guess the project has no copilot? Either way, I created this TCX issue:
https://github.com/jmgasper/TCX-Test4/issues/54, opened it, assigned it, and closed it out. In WM, i see:

![Screen Shot 2021-02-19 at 5 08 10 AM](https://user-images.githubusercontent.com/5400156/108490382-b2681000-7270-11eb-864f-d113854b7485.png)

Which shows a copilot payment with no copilot assigned. 

In pacts, I see:
![Screen Shot 2021-02-19 at 5 10 27 AM](https://user-images.githubusercontent.com/5400156/108490512-d166a200-7270-11eb-81ca-f207f4b01e0d.png)

**Comment by jmgasper** [comment]
@rootelement - This doesn't make much sense to me.  I see the copilot in `/v5/resources` for https://api.topcoder-dev.com/v5/resources?challengeId=649a90da-7b43-4560-8ccc-ba3ce1ee5f00

(copilot is `sdgun`, and the role ID looks correct)

But, it's not showing up in WM?

**Comment by jmgasper** [comment]
Could this be a problem in WM?  Looks like it got into PACTs correctly.  I tried with a different copilot (`sdgun`), just to see if it was a problem with the TonyJ user, but saw the same thing.
