### ISSUE TITLE
Internal reviewer

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#399]
### Problem

Currently, challenges created by Topcoder-X can't be edited in work manager (challenges.topcoder-dev.com)

### Solution

We need to add an internal reviewer to tasks created by Topcoder-X.  The internal reviewer can be set to the copilot on the Topcoder-X project.

**Comment by afrisalyp** [comment]
@jmgasper 

How do we add the internal reviewer data into the topcoder challenge?

Can we use the POST `/resources` API?

**Comment by jmgasper** [comment]
Yes, we should use the POST to `/resources`

You can get the roles available from `GET https://api.topcoder-dev.com/v5/resource-roles`

And we can configure the role ID, similar to what we already for things like the copilot role.

For this, let's set the copilot as the `iterative reviewer` role.
