### ISSUE TITLE
Git access link not working for Github

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#40]
I created this link, but it's not working as expected:

https://x.topcoder.com/api/v1/github/teams/registration/48c2ed06-ab53-4dee-a98b-eebcde50f17b-1532985120810 

The error the member is seeing:

```
I am getting this error: '"Failed to add team member. 422 error making request PUT 
https://api.github.com/teams/2842481/memberships/krunt: "Unprocessable Entity"."
```

**Comment by cwdcwd** [comment]
FWIW I've seen that on the Ragnar links too when the originating link creator does not have rights to add a member to the Github Organization. While they might be able to add them to teams I don't think they can add them to the org. 
At least that's what my suspicion is for this particular error based on my fuzzy memory and poor research. =)

**Comment by jmgasper** [comment]
@cwdcwd - That description makes sense, but how do we work around that for things like the topcoder-platform group?

**Comment by cwdcwd** [comment]
no entirely sure. need to think on it some more. part of it depends on the user accepting the invite too which makes things wonky

**Comment by mishacucicea** [comment]
@jmgasper if #111 is fixed, than this would be ok as well, right?
I mean whoever creates the github link needs to have access to add members to the Org and Team.

**Comment by jmgasper** [comment]
@mishacucicea - Yeah, that's pretty much the idea, yes.
