### ISSUE TITLE
"Open for pick up" ticket not showing in Dashboard

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-x-ui#41]
Competitors - note the steps below, especially the distinction that this was an existing ticket.

STR:
- set up the TCX project for the [repo](https://github.com/topcoder-platform/community-app) including webhooks and labels
- took an [existing ticket](https://github.com/topcoder-platform/community-app/issues/1156) and set its prize money and labeled "Open for Pickup" 
- Challenge eventually created for ticket
- No ticket in Dashboard

![image](https://user-images.githubusercontent.com/1504607/43979390-a2e99242-9cb8-11e8-90db-1018178b1851.png)

**Comment by jmgasper** [comment]
Hmmm.... I wonder if this was because it was an existing ticket vs. new.  I'll add this to a bug bash challenge to investigate

**Comment by cwdcwd** [comment]
thanks. it __did__ seem to pick up eventually which maybe there was a challenge API issue but would be good to know definitively what's going on there.

**Comment by rootelement** [comment]
FYI - I created a new issue on my repo and added the label and it wasn't picked up either. The label was added on create of a new issue.

My Assigned issue showed up when I added the label to an already existing, and already assigned issue. So it's something with this label specifically.

**Comment by jmgasper** [comment]
Recent review feedback:

I can reproduce the issue, this is not fixed.

Screencast: https://drive.google.com/file/d/1O6-vD99MsUK98uv21o9mSEJkDWia18cX/view?usp=sharing


Steps:

1. Create a repo and add an issue without prize in the title.
2. Create a project in TCX that points to the repo you just created.
3. Update the issue name to include a prize and add "tcx_OpenForPickup" label.
4. The TCX Receiver will show these logs:
```
debug: { event: 
  { event: 'issue.updated',
    provider: 'gitlab',
    data: { issue: [Object], repository: [Object] } } }
debug: ENTER getRepositoryCopilot
debug: input arguments
debug: { provider: 'gitlab', repoFullName: 'monicamuranyi/tc-x-ui-1' }
debug: EXIT getRepositoryCopilot
debug: output arguments
debug: { accessToken: '<removed>',
  userProviderId: 43305,
  topcoderUsername: 'mess' }
debug: Scheduling event for next retry
error: Error happened in process
ProcessorError: there is no challenge for the updated issue 2
    at Object.internalDependencyError (/home/moni/Projects/review/tc-x-ui/submission-260035-submission/topcoder-x-processor/utils/errors.js:96:20)
    at ensureChallengeExists (/home/moni/Projects/review/tc-x-ui/submission-260035-submission/topcoder-x-processor/services/IssueService.js:130:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error:  message=there is no challenge for the updated issue 2, stack=ProcessorError: there is no challenge for the updated issue 2
    at Object.internalDependencyError (/home/moni/Projects/review/tc-x-ui/submission-260035-submission/topcoder-x-processor/utils/errors.js:96:20)
    at ensureChallengeExists (/home/moni/Projects/review/tc-x-ui/submission-260035-submission/topcoder-x-processor/services/IssueService.js:130:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7), name=ProcessorError, statusCode=500, errorAt=processor, logged=true
```
