### ISSUE TITLE
Display how many hours a ticket has been assigned

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#44]
Since members only have 24 hours to complete a ticket, we'd like the ability to show how long a ticket has been assigned in the UI.  

### UI

On the dashboard, we will add a new column to the `Assigned` and `Ready for review` tables called `Hours Assigned`.  This will be the number of hours since the ticket was marked as `Assigned`.  Please use a bold font for the value.

* For tickets that are <18 hours assigned, we'll show the number of hours in green.  
* For tickets that are >18 hours assigned but less than 24 hours, we'll show the number of hours in yellow.  
* For tickets that are > 24 hours assigned, we'll show the number in red.

**Comment by cwdcwd** [comment]
I wonder if we could run some sort of a Cron-like job and then post labels or comments?
