### ISSUE TITLE
Automatically Create a help page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/topcoder-x-ui#45]
Create a `Help` page that will list the required labels we have to use.

For example, in many of my projects, I’m using the following structure http://take.ms/6USYQ which is slightly different.

### Functionality

In `Edit` for a Project, we currently have two buttons:

* Add Labels
* Add Webhook

This ticket will track adding a 3rd option - `Add wiki rules`.

When this button is clicked, we will add a new wiki page to the repository with the contents of a file read from the file system (if possible).  The page should be titled `WorkingWithGitTickets`

Here's the default text we will add:

[WorkingWithTickets.md.zip](https://github.com/topcoder-platform/topcoder-x-ui/files/2334726/WorkingWithTickets.md.zip)

**Comment by cwdcwd** [comment]
we could probably post the TC rules to the wiki for a repo when we do the set up in the Admin UI.

**Comment by jmgasper** [comment]
New we have a `Add Wiki Rules` button that will add a `Gitlab ticket rules` wiki page to Gitlab repos and a similar issue to Github projects (Github doesn't have a proper wiki-editing API)
