### ISSUE TITLE
User Terms Agreement

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-x-ui#46]
A user assignment will be blocked if the user hasn't previously agreed to the terms. 
We should probably check the terms for the user when executing the member add link for a member.
I believe this can be fetched from the member profile endpoint

**Comment by jmgasper** [comment]
@cwdcwd / @rootelement - Can you point me to the member API please?  I'll investigate the call needed.

**Comment by jmgasper** [comment]
@rootelement ☝️

**Comment by jmgasper** [comment]
@cwdcwd / @rootelement - Not sure what API to use here.  Can you help please?

**Comment by jmgasper** [comment]
@cwdcwd / @rootelement  - My yearly checkin on this ;).  Is there a good v5 API we can use for this?  ☝️
