### ISSUE TITLE
[$75] Private fork review items

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#474]
@dhruvit-r - A couple items here to tweak:

1.  Can we move the Kafka handler and PrivateForkService to the Topcoder-x-processor please?  I think that'll make more sense as that processor is what handles the "processing" for the tool.  I'd prefer to keep the UI processor-free.

2. I can't seem to access the UI after the latest fix. It's in a redirect loop.  I deployed the previous build to double check and it is working fine, so this was caused by the latest changes.

```
v14.21.3 ❯ curl -v https://x.topcoder-dev.com
*   Trying 54.173.86.201:443...
* Connected to x.topcoder-dev.com (54.173.86.201) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.topcoder-dev.com
*  start date: Feb  3 07:27:30 2023 GMT
*  expire date: Feb  1 13:14:00 2024 GMT
*  subjectAltName: host "x.topcoder-dev.com" matched cert's "*.topcoder-dev.com"
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: x.topcoder-dev.com]
* h2 [:path: /]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: */*]
* Using Stream ID: 1 (easy handle 0x15b811400)
> GET / HTTP/2
> Host: x.topcoder-dev.com
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/2 302
< date: Mon, 28 Aug 2023 05:30:52 GMT
< content-type: text/plain; charset=utf-8
< content-length: 23
< x-powered-by: Express
< access-control-allow-origin: *
< location: /
< vary: Accept
< set-cookie: connect.sid=s%3AMltguFcTHZzFKpTG7buw9CoGNc_Edf5-.UKtNTrbVpXMGtlZjnRC%2FbsQDr8r%2BEpT9zA8N7Ufe5IQ; Path=/; HttpOnly
<
* Connection #0 to host x.topcoder-dev.com left intact
Found. Redirecting to /
```

**Comment by dhruvit-r** [comment]
@jmgasper
1. It seems like PrivateForkService and Kafka Handler are already a part of the processor?
    - https://github.com/topcoder-platform/topcoder-x-processor/pull/108/files#diff-04d67ab946290bb476a065acdf7257c7b79459225739c3800c83c425ccaabf17
    - https://github.com/topcoder-platform/topcoder-x-processor/pull/108/files#diff-b59aa23eb1a035972f65e2699e0a099aaec6037e08468bce6b1f26cd8605b7e2R104
1. Alright if we deploy the new UI again? I need to run some tests to figure out what's going wrong. And is there a way to access the logs from the dev environment?

**Comment by jmgasper** [comment]
@dhruvit-r - 

1.  My bad, not sure why I saw those in the UI 🤷 
2. Yep, anytime we check into the `develop` branch, it will redeploy to x.topcoder-dev.com.  I'm wondering if this is due to changing the node, Dockerfile, or gulp details?
