### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-x-ui#49]
We should write a set up guide for how to get running

**Comment by jmgasper** [comment]
@cwdcwd - Running in general for copilots, or actually deployed?

I have deployment documented:  https://github.com/topcoder-platform/topcoder-x-ui/blob/develop/TopcoderXDeploy.md

**Comment by rootelement** [comment]
Couple of notes for my first time setting up a project with no prior knowledge of the steps required:

1. On the Dashboard page, if there are no Projects, show a "getting started" box
2. Getting Started Box should say
  1. Authorize GitHub / GitLab
  2. Add a Project
  3. Add Labels and Webhooks to Project (show a screenshot - this was unclear that I had to go back into the project to add them, or at least the buttons were non-obvious)
2. On the Add Project page - add descriptions to the form
  1. Direct ID: Show an example URL and allow the user to paste the full URL if possible
  2. Repo URL is a little unclear... (these questions are for Gitlab) Can you add a group URL (https://gitlab.com/group)? Just a repo (https://gitlab.com/group/repo)? What about a branch URL (https://gitlab.com/group/repo/tree/develop)? Is the URL validated on save?
  3. It's unclear what Archived means? Issues won't show up in the Dashboard anymore?

**Comment by jmgasper** [comment]
This is great, thanks!  I'll look through this and log some UI changes.

**Comment by cwdcwd** [comment]
@jmgasper docs for end user to get setup like clients/CPs
