### ISSUE TITLE
Help link

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#52]
For basic help, we'll use the Topcoder-X UI wiki.  Please add a `Help` button to the bottom of the side bar that opens a new window with a configurable URL.  The URL should be configurable through the environmental variables so that we can use the Heroku settings (`heroku config:set ...`) to change the URL when necessary.

Use the `question-circle` font-awesome icon.

* Default: https://github.com/topcoder-platform/topcoder-x-ui/wiki

![screen_shot_2018-08-30_at_1_59_13_pm](https://user-images.githubusercontent.com/21790/44828858-23f51380-ac5d-11e8-9924-25ed05d46037.jpg)

**Comment by cwdcwd** [comment]
we could also get crazy go nuts and do [github pages](https://help.github.com/categories/github-pages-basics/)
