### ISSUE TITLE
Copilot payments: Fix amount

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#56]
From the most recent review:

Spec mentions  `If a prize is required, we can set it to $1 and decrease the value of the copilot payment by $1`. This case is not handled correctly, I don't see the copilot payment being reduced by $1

**Comment by kevinkid** [comment]
For people looking into this here is the spec. https://github.com/topcoder-platform/topcoder-x-ui/issues/22
