### ISSUE TITLE
Search Git Groups

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/topcoder-x-ui#63]
I belong to fewer groups than most, and still have 4 pages. Add a simple search bar at the top to narrow down the groups.
![screen shot 2018-08-28 at 10 21 59 am](https://user-images.githubusercontent.com/5400156/44729208-4b58ae80-aaac-11e8-9bef-bb9a3c001188.png)

**Comment by jmgasper** [comment]
@rootelement - This is done, I just forgot to close the ticket.  Can be seen in dev.

<img width="714" alt="Screen Shot 2019-10-01 at 2 51 57 am" src="https://user-images.githubusercontent.com/21790/65899160-7b345d00-e3f6-11e9-9395-c61831c02d1d.png">
<img width="714" alt="Screen Shot 2019-10-01 at 2 51 45 am" src="https://user-images.githubusercontent.com/21790/65899163-7bccf380-e3f6-11e9-996e-e217925ba883.png">
