### ISSUE TITLE
Copilot Payments table changes

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#68]
A few tweaks are needed to make the copilots page a bit more usable:

1.  The amount should have `$` before the number, so instead of `75`, it would display `$75`

2.  Above the table we should have text that sums the amounts pending, in bold.  Something like `$250 total pending payments`.

**Comment by veshu** [comment]
@jmgasper for points 2 this means all project's payments right?

**Comment by jmgasper** [comment]
@veshu - That's correct - this will be a sum of *all* pending payments across all projects.
