### ISSUE TITLE
Preventing issue assignment

### ISSUE THREAD

**Issue by dustinTopcoder** [topcoder-platform/topcoder-x-ui#76]
On one of our projects, a member assigned themselves to some issues before they had a bounty.  As such, before we could put the "Open for pickup" label, we had to manually unassign the issues.

Would be nice if the following workflow happened:

1. When an issue has been edited with a bounty but missing the "Open for pickup" label, prevent anyone from being assigned the issue and clear any previous assignments (reset the issue).  If someone attempts to assign themselves, just auto-remove them with a friendly comment about the issue not being ready yet.
1. When the "Open for pickup" label is added, allow people to assign themselves to the issue.

**Comment by jmgasper** [comment]
👍

**Comment by dustinTopcoder** [comment]
Another thought I had on this.  Add a new label called "Not ready".  This would be used to tag any issues you wish to have as part of the bounty system, but not ready for pickup yet.  So any issue with this label would follow the workflow I put above.

My reasoning is that there are some issues you may have being worked externally and my original idea would not allow that.
