### ISSUE TITLE
Don't remove labels when closing a ticket

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-ui#92]
When marking a ticket as `tcx_Paid`, we should just add that label, not removing all others.  Users are seeing their custom labels (not TC-X related) getting removed as well.

![generate_image_preview](https://user-images.githubusercontent.com/21790/45921588-f158d680-befb-11e8-9aff-064e91576d2a.png)

**Comment by veshu** [comment]
@jmgasper looks like this again issue https://github.com/topcoder-platform/community-app/issues/3113#issuecomment-516720191

**Comment by jmgasper** [comment]
@veshu - That's strange.  I'll keep an eye on it, thanks.
