### ISSUE TITLE
Bypass Github invitation process

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/topcoder-x-ui#97]
A very common issue is that if a member is not in the Github organization, we can't add the member to a team thus the member can't work on any ticket.

Maybe we can use this https://developer.github.com/v3/repos/invitations/#accept-a-repository-invitation and then grab an oAuth token so we can auto accept the invitation.

cc @jmgasper

**Comment by jmgasper** [comment]
Dupes #111
